[package]
name = "as_num"
version = "0.2.6"
authors = ["philipp <philipp>"]
description = "Checked conversions between Rust's numeric types."
license = "MIT/Apache-2.0"
repository = "https://github.com/phimuemue/rs_as_num"
documentation = "https://docs.rs/as_num"

[dependencies]
